version: "3.7"
services:
  ubuntu-neovim-dein:
    volumes:
      - /home/takabatakekoichi/development/swatch_erp:/kowa-swatch:delegated
      - "~/development/react-native-practice:/react-native-practice:delegated"
