version: "3.7"
services:
  ubuntu-neovim-dein:
    volumes:
      - docker_kowa:/kowa-swatch:delegated
      - /kowa-swatch/app/tmp/cache/
      - /kowa-swatch/node_modules/
      - /kowa-swatch/public/packs/
      - /kowa-swatch/public/assets/
      - /kowa-swatch/tmp/

volumes:
  docker_kowa:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/Users/takabatakekoichi/kowaprojects/swatch_erp"
